### ISSUE TITLE
Fargate support for initializing Envoy

### ISSUE THREAD

**Issue by jamsajones** [awslabs/aws-app-mesh-examples#24]
Currently you cannot get elevated permissions in on a Fargate instacnce to change the iptables rules and route all traffic (ingress and egress) through Envoy.

**Comment by ranga543** [comment]
Is it fair to assume `App Mesh` does not support `AWS Fargate` yet ?

**Comment by jamsajones** [comment]
@ranga543 App Mesh does not support AWS Fargate yet. Running the aws-appmesh-proxy-route-manager requires NET_ADMIN which is not availble in Fargate. We are working with the Fargate team to solve this problem as soon as possible.

**Comment by johnnorton** [comment]
Is there a way to configure the service container to use then envoy proxy so we don't have to change IPTables?

**Comment by jamsajones** [comment]
Closing in favor of issue #15.
