### ISSUE TITLE
Clarification of "serviceNames" field across virtualRouter and virtualNodes

### ISSUE THREAD

**Issue by zbintliff** [awslabs/aws-app-mesh-examples#49]
From my understanding the [`"serviceNames"` in virtualRouters](https://github.com/awslabs/aws-app-mesh-examples/blob/master/examples/apps/colorapp/servicemesh/config/virtualrouters/colorteller-virtualrouter.json#L4) appmesh updates for you to point to the virtualRouters you define. That is if you define serviceNames "a" and "b" it will update the records in AWS Service discovery to point to your virtualRouters.

However, in the ["serviceName"](https://github.com/awslabs/aws-app-mesh-examples/blob/master/examples/apps/colorapp/servicemesh/config/virtualnodes/colorteller-black-virtualnode.json#L13) referenced here it is purely referential and lookup based.

I was conflating the two thinking they were _both_ referential (i.e. the service names the router will point _to_)

Is my current understanding correct?

**Comment by bcelenza** [comment]
The serviceNames used in App Mesh are referential -- that is they allow you to define what VirtualNodes you want to represent a given serviceName, and what VirtualRouter routes traffic for that serviceName. We use these references to tie together nodes and routes into CDS Clusters/RDS Routes, respectively.

For actually registering your AWS Service Discovery namespaces and endpoints, ECS handles that today (see example [namespace](https://github.com/awslabs/aws-app-mesh-examples/blob/master/examples/infrastructure/ecs-cluster.yaml#L364-L369), [discovery record](https://github.com/awslabs/aws-app-mesh-examples/blob/master/examples/apps/colorapp/ecs/ecs-colorapp.yaml#L42-L54), and [ECS service registration](https://github.com/awslabs/aws-app-mesh-examples/blob/master/examples/apps/colorapp/ecs/ecs-colorapp.yaml#L66-L68)). Once those are defined new tasks will register themselves as a service instance.

**Comment by zbintliff** [comment]
Sorry if my question wasn't clear. The `serviceName` in the router only represents the VirtualRouter itself not the services behind it. The namespace already exists (i see it created in the template). The nodes associated in the route can any other service?

To me it seems like the Virtual Router can receive traffic for `colorteller` but routes it to the `black/blue` (for canary).  Meaning the design looks like:

```
                                                             _ 80% `colorteller-black-vn` -> colorteller-black.local
colorteller.local -> `colorteller-vr` -> `colorteller-route`<
                                                             - 20% `colorteller-blue-vn` -> colorteller-blue.local
```

**Comment by bcelenza** [comment]
Sorry for misunderstanding the initial question. It seems like your understanding (and example design) is correct. 

Could you clarify this question specifically, just so I'm sure?
> The nodes associated in the route can any other service?

**Comment by zbintliff** [comment]
Forgot a word! Supposed to read "The nodes associated in the route can **be** any other service?"

As in, the VirtualRouter can have service name `colorteller` but the Nodes in the Route assigned to the Router can be for service names `foo` and `bar`

**Comment by kiranmeduri** [comment]
Yes, the service-names defined in virtual-router act as virtual-hosts in Envoy. A virtual-host can eventually route to a destination that is serving at different name. In most normal scenarios virtual-router and virtual-node are 1:1. In cases where a monolith is being migrated to component services, this separation will allow consumer virtual-nodes to be isolated from the change. For example store.example.com can be the service-name used in virtual-router with routes to cart.example.com, details.example.com being defined based on paths "/cart" and "/details" respectively. We are looking for ways to simplify this for the majority of cases.

**Comment by zbintliff** [comment]
With all the tools there then, making envoy a front proxy is only a step or two away (minus the restrictions on input/output) to make it dynamic rather than an route update.

**Comment by kiranmeduri** [comment]
(theoretically) yes, more on this will be discussed on #31 . For now closing this. Please re-open if you need more information. Thank you
