### ISSUE TITLE
Updates to routes have no effect on running envoys 

### ISSUE THREAD

**Issue by kiranmeduri** [awslabs/aws-app-mesh-examples#54]
**What happened?**

Updates to routes have no effect on running envoys 

**What you expected to happen?**

Tasks must be restarted for route changes to take effect.

**How to reproduce it (as minimally and precisely as possible)?**

_Not easy to reproduce as it happens sporadically. Seems to be an issue with XDS protocol_

1. Create two virtual-nodes with a route between them (A→B).  
2. Verify the route is working by making requests to A.   
3. Create a new version for B (say B2).
3.  Update the route by changing weights.
4.  Check if A is now routing some traffic to B2 based on weights. 

Observed that it does not, though you may need to try to change the routes a few times and leave A running for an extended period of time (>30mins).

Issue gets resolved if I restart A as it gets new configuration.

**Comment by bcelenza** [comment]
This issue should now be resolved in all production regions. Please re-open if the issue recurs.
