### ISSUE TITLE
Information Request: Virtual Router serviceName

### ISSUE THREAD

**Issue by nefilim** [awslabs/aws-app-mesh-examples#71]
Hi 

Saw this issue: https://github.com/awslabs/aws-app-mesh-examples/issues/49 but still not very clear to me (new to ECS also). 

What exactly does spec.serviceNames refer to? From this example, it appears to refer to a [DNS record created by the ECS Service Discovery](https://github.com/awslabs/aws-app-mesh-examples/blob/master/examples/apps/colorapp/ecs/ecs-colorapp.yaml#L51)

What is the spec.serviceNames used for internally? 

Since Routes can reference [multiple discrete Virtual Nodes](https://github.com/awslabs/aws-app-mesh-examples/blob/master/examples/apps/colorapp/servicemesh/config/update_routes/colorteller-route-black-80-blue-20.json#L6) ie. multiple discrete ECS Services - does this mean one need to update the Virtual Router's spec.serviceNames to include all the services referenced in the associated routes? 
This doesn't appear to be the case, updating the routes with the above linked routes (refers to both black & blue services) but the Virtual Router still just refers to: 

```
        "spec": {
            "serviceNames": [
                "colorteller.peteram.svc.cluster.local"
            ]
        },
```

which actually doesn't correspond to either of the Virtual Nodes referenced in the routes? So it seems somewhat meaningless?

Would be great to expand the documentation to specify *exactly and verbosely* what each element refers to. 

Thanks!

**Comment by lavignes** [comment]
@nefilim

This is definitely an area we're looking to help clarify for our customers. We're compiling some information that might help. We'll update this issue when its ready.

But quickly:

> does this mean one need to update the Virtual Router's spec.serviceNames to include all the services referenced in the associated routes?

Yes. All serviceNames need to be referenced. The virtual nodes in this example should have a `spec.serviceDiscovery.dns.serviceName` of `colorteller-black.colorteller.peteram.svc.cluster.local` and `colorteller-blue.colorteller.peteram.svc.cluster.local`.

**Comment by nefilim** [comment]
Thank you, that added some useful colour.

**Comment by ivitjuk** [comment]
No problem, closing this. Let me know if there is anything else I can help with.
