### ISSUE TITLE
[BUG] Can't Setup EKS Cluster

### ISSUE THREAD

**Issue by shibataka000** [awslabs/aws-app-mesh-examples#78]
**Describe the bug**
I setup EKS Cluster, but EKS Cluster has no worker node.

**Platform**
EKS

**To Reproduce**
Setup Infrastructure according to [examples](https://github.com/awslabs/aws-app-mesh-examples/tree/master/examples).

1. Export environment variables.
2. Setup Infrastructure. Make sure status of CloudFormation stack is `CREATE_COMPLETE`.

```
$ ./infrastructure/vpc.sh create-stack
$ ./infrastructure/mesh.sh 
$ ./infrastructure/eks-cluster.sh create-stack
```

3. Prepare to use EKS Cluster according to [Getting Started with Amazon EKS](https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html).

```
$ aws eks update-kubeconfig --name ${ENVIRONMENT_NAME}"
$ kubectl apply -f aws-auth-cm.yaml
```

4. Try to find k8s worker node.

```
$ kubectl get node
No resources found.
```

**Expected behavior**
I expect that I can get some k8s worker node.

**Config files, and API responses**
None

**Additional context**
I can setup EKS Cluster completely by updating EKS Optimized AMI from `ami-0a0b913ef3249b655` to `ami-0440e4f6b9713faf6` in us-east-1. I think AMI is old probably.

**Comment by shibataka000** [comment]
I made sure EC2 Instance as worker nodes were launched. I logged in worker node and checked status of kubelet.

```
[root@ip-10-0-65-85 log]# systemctl status kubelet
● kubelet.service - Kubernetes Kubelet
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           mq10-kubelet-args.conf, 20-max-pods.conf
   Active: activating (auto-restart) (Result: exit-code) since Fri 2019-01-18 07:24:24 UTC; 3s ago
     Docs: https://github.com/kubernetes/kubernetes
  Process: 4410 ExecStart=/usr/bin/kubelet --address=0.0.0.0 --authentication-token-webhook --authorization-mode=Webhook --allow-privileged=true --cloud-provider=aws --cluster-domain=cluster.local --cni-bin-dir=/opt/cni/bin --cni-conf-dir=/etc/cni/net.d --container-runtime=docker --network-plugin=cni --cgroup-driver=cgroupfs --register-node=true --kubeconfig=/var/lib/kubelet/kubeconfig --feature-gates=RotateKubeletServerCertificate=true --anonymous-auth=false --client-ca-file=/etc/kubernetes/pki/ca.crt $KUBELET_ARGS $KUBELET_MAX_PODS $KUBELET_EXTRA_ARGS (code=exited, status=255)
 Main PID: 4410 (code=exited, status=255)
Jan 18 07:24:24 ip-10-0-65-85.ec2.internal systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
Jan 18 07:24:24 ip-10-0-65-85.ec2.internal systemd[1]: Unit kubelet.service entered failed state.
Jan 18 07:24:24 ip-10-0-65-85.ec2.internal systemd[1]: kubelet.service failed.
```

kubelet was failed.

**Comment by bcelenza** [comment]
Thanks for reporting @shibataka000. We're looking at all of your PRs this week. Just wanted to give you an update on that. Thanks for all your contributions so far. 👍

**Comment by Y0Username** [comment]
@shibataka000 Looked into this and it doesn't seem to be AMI problem. EKS Cluster should be active before creation of worker nodes. This PR #84 should fix it.

**Comment by bcelenza** [comment]
Merged. @shibataka000 Can you retry from the latest in `master` and re-open if you still see the issue?
