### ISSUE TITLE
[BUG] colorgateway does'nt work in EKS

### ISSUE THREAD

**Issue by shibataka000** [awslabs/aws-app-mesh-examples#81]
**Describe the bug**
k8s pod of colorgateway fail repeatedly.

**Platform**
EKS

**To Reproduce**
1. Setup infrastructure according to [examples](https://github.com/awslabs/aws-app-mesh-examples/blob/master/examples/README.md).
2. Deploy color-teller and color-gateway to EKS according to [colorapp](https://github.com/awslabs/aws-app-mesh-examples/blob/master/examples/apps/colorapp/README.md).

```
$ ./kubernetes/generate-templates.sh && kubectl apply -f ./kubernetes/colorapp.yaml
```

3. Pod of colorgateway fail repeatedly.

**Expected behavior**
colorgateway work correctly as described in [colorapp](https://github.com/awslabs/aws-app-mesh-examples/blob/master/examples/apps/colorapp/README.md).

**Config files, and API responses**
colorgateway pod log is below.

```
$ kubectl logs colorgateway-64bdb8d55-rhl4b colorgateway 
2019/01/19 02:01:47 Sleeping for 60s to allow Envoy to bootstrap
2019/01/19 02:02:47 Starting server, listening on port 9080
2019/01/19 02:02:47 TCP_ECHO_ENDPOINT is not set
```

**Additional context**
None

**Comment by Y0Username** [comment]
Thanks @shibataka000. Merged #82. Closing this.
