### ISSUE TITLE
[BUG] Routes to Target Virtual Nodes with Mismatched Ports Blackhole

### ISSUE THREAD

**Issue by dastbe** [awslabs/aws-app-mesh-examples#93]
**Describe the bug**

When a Route targets Virtual Nodes whose listeners do not agree on the port, App Mesh
will fail to create a route in the Envoy configuration distributed to clients.

For example, the following Route

```
aws appmesh describe-route --mesh-name test-mesh --virtual-router-name test-router --route-name test-route
{
    "route": {
        "status": {
            "status": "ACTIVE"
        },
        "meshName": "test-mesh",
        "virtualRouterName": "test-router",
        "routeName": "test-route",
        "spec": {
            "httpRoute": {
                "action": {
                    "weightedTargets": [
                        {
                            "virtualNode": "vn-1", // Listens on port 8080
                            "weight": 1
                        },
                        {
                            "virtualNode": "vn-2", // Listens on port 8081
                            "weight": 1
                        }
                    ]
                },
                "match": {
                    "prefix": "/"
                }
            }
        }
}
```

would not be distributed down to an Envoy subscribed to the Virtual Router. Worse, there is nothing in App Mesh APIs or Envoy configuration that would alert you that the route is not being distributed.

**Platform**
ALL

**Expected behavior**

Some possible solutions

1. Provide synchronous checking in create-route/update-route to enforce all Virtual Nodes have the same listener port. This would not disallow changing listener ports after the fact.
2. Provide asynchronous events or messages in API calls alerting customers that this route will not be materialized.
3. Provide a mechanism to abstract Virtual Router listener ports from target Virtual Node listener ports

**Comment by bcelenza** [comment]
This has been resolved with a new API revision released in the following SDKs:

CLI: 1.16.120
Java: 1.11.514
Java (V2): 2.5.5 2019-03-07
CPP: 1.7.65
Go: 1.17.13
PHP: 3.89.0
Python: 1.9.110
JavaScript: 2.417.0
Ruby: 2.11.236
.NET: 3.3.471.0
