### ISSUE TITLE
Configuring stats sinks

### ISSUE THREAD

**Issue by seubert** [awslabs/aws-app-mesh-examples#95]
First off, I'm not super well versed in Envoy nor Envoy configuration so apologies if this is an obvious answer. I'd like to configure the App Mesh Envoy deployment to use the `envoy.dog_statsd` sink to pull out Envoy metrics. However, I am not sure how to do this with App Mesh, specifically using the colorapp example as a sandbox. Is this a configuration lever that I have access to when using App Mesh? Looking at `generate_templates.sh` I don't see any way of inserting config and I don't see anything in the App Mesh APIs to add to the dynamic config either. Thanks!

**Comment by bcelenza** [comment]
Hey @seubert,

The `envoy.dog_statsd` sink is configured within the bootstrap configuration of Envoy (i.e. before it can reach out to our systems for dynamic configuration). At the moment, our bootstrap configuration is distributed with the `111345817488.dkr.ecr.us-west-2.amazonaws.com/aws-appmesh-envoy:v1.8.0.2-beta` docker image. 

It is possible to provide a separate bootstrap config to Envoy that would contain the proper sink settings. We have not yet published the Dockerfiles and build scripts for this image (#59), but I can point you in the right direction if you're interested in pursuing this approach.

Alternatively, we are actively working on making DogStatsD configuration easier (#7), and should have an update in this area in the coming weeks, so please watch that issue as well and provide any feedback or use cases of interest there.

**Comment by seubert** [comment]
Thanks @bcelenza. More info on how to properly provide a separate bootstrap config would be great. Right now I've just copied the generated config from the running Envoy containers, added my own settings, and mounted it at /tmp/envoy.yaml to "override" the generated one. This works but isn't particularly clean and depends on your Dockerfiles/build scripts not changing config path etc.

Thanks for the links to those other issues, I'll keep an eye on them as well.

**Comment by ivitjuk** [comment]
@seubert in addition to providing the whole bootstrap file by yourself, you can create a file with stats config only, mount it in the Envoy container, and pass environment variable `ENVOY_STATS_CONFIG_FILE` to the container with the full path to the stats config file as it's value.

Our bootstrap script will then detect `ENVOY_STATS_CONFIG_FILE` variable and include the referenced file into the generated Envoy bootstrap config.

Your stats config should include   `stats_sinks` and `stats_config` bootstrap sections.

**Comment by bcelenza** [comment]
Given the discussion in #98 I'm assuming we've resolved this particular question, so closing the issue. Please re-open if you have any additional configuration issues.
