### ISSUE TITLE
Configuring Zipkin Tracing

### ISSUE THREAD

**Issue by achandras** [awslabs/aws-app-mesh-examples#99]
Apologies if this is already covered elsewhere, but is there a variable that can be configured to pick up a Zipkin tracing config for Envoy, similar to https://github.com/awslabs/aws-app-mesh-examples/issues/95#issuecomment-470188986? In the Envoy logs, there is a line that says `loading trace configuration`, so I gave it a shot by setting `ENVOY_TRACING_CONFIG_FILE`, but I couldn't see anything in the logs to indicate that the file was being picked up. What would be the correct setting? Thanks!

**Comment by ivitjuk** [comment]
@achandras variable name for injecting tracing config is `ENVOY_TRACING_CFG_FILE`. You can verify if the content was injected into the Envoy bootstrap file by doing `cat /tmp/envoy.yaml` inside the Envoy container, unless you provide your own Envoy config file location via `ENVOY_CONFIG_FILE`.

**Comment by achandras** [comment]
Thank you, @ivitjuk!

**Comment by janaka** [comment]
FYI - used this config override to add Zipkin tracing config to Envoy and using that with an OpenTelemetry agent/collector.
